### ISSUE TITLE
应用商店无法安装

### ISSUE THREAD

**Issue by wangxiaofan999** [brokyz/Win10_LTSC_2021_FixPacks#1]
应用商店无法安装，报错如下：
![image](https://user-images.githubusercontent.com/22412809/171068298-d46d8f8c-035f-48b0-a030-cc9f92ddfaf8.png)

add-appxpackage : 部署失败，原因是 HRESULT: 0x80073CFD, 无法满足安装的先决条件。
由于程序包 Microsoft.WindowsStore_22204.1401.3.0_x64__8wekyb3d8bbwe 与设备不兼容，Windows 无法安装该程序包。该程序包要
求 Windows.Mobile 设备系列运行操作系统版本 10、0、18363、0 或更高版本。该设备当前运行的操作系统版本为 10、0、17763、292
8。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] fd2ed547-71db-0002-0430-32fddb71d801，或使用命令行 Get-AppPackageLo
g -ActivityID fd2ed547-71db-0002-0430-32fddb71d801
所在位置 行:1 字符: 1
+ add-appxpackage F:\Download\Win10_LTSC_2021_FixPacks\Add-Store\Micros ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (F:\Download\Win...bbwe.Msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by brokyz** [comment]
请检查系统版本，本脚本是为win10 LTSC 2021版本写的，版本号应该是21H2。
